/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI;

import Entity.ParkCntrl;
import javax.swing.JButton;
import javax.swing.JOptionPane;

/**
 *
 * @author Yongli Wang
 * @author Jingtai Li
 */
public class OperatorDialog extends javax.swing.JDialog {
     ParkCntrl op;
    /**
     * Creates new form Operator
     * @param parent
     * @param modal
     * @param op
     */
    public OperatorDialog(java.awt.Frame parent, boolean modal,ParkCntrl op) {
        super(parent, modal);
        this.op=op;
        initComponents();
        this.currentCashRefresh();
        this.currentTicketRefrsh();
        this.setVisible(true);
    }
    
    /**
     * refresh labels of current cash
     */
    public void currentCashRefresh(){
        int state[]=op.cashBoxState();
        int m50c =state[0];
        int m1p  =state[1];
        int m2p  =state[2];
        String currentCashState="Current Cash: 50c:"+m50c+" 1p: "+m1p+" 2p: "+m2p;
        this.CurrentCash.setText(currentCashState);
    }

    /**
     *refresh labels of current ticket state
     */
    public void currentTicketRefrsh(){
        int ticketLeft=op.ticketBoxState();
        String currentTicketState="Current Ticket: "+ticketLeft;
        this.CurrentTic.setText(currentTicketState);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        CurrentCash = new javax.swing.JLabel();
        CollectBut = new javax.swing.JButton();
        FillBut = new javax.swing.JButton();
        CurrentTic = new javax.swing.JLabel();
        SendBut = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("System Operator");

        CurrentCash.setText("Current Cash: ");

        CollectBut.setText("Collect");
        CollectBut.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CollectButMouseClicked(evt);
            }
        });

        FillBut.setText("Fill");
        FillBut.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                FillButMouseClicked(evt);
            }
        });

        CurrentTic.setText("Current Ticket:");

        SendBut.setText("SEND!");
        SendBut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SendButActionPerformed(evt);
            }
        });

        jLabel2.setText("Generate all Bills");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jSeparator1))
            .addComponent(jSeparator2, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(94, 94, 94)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(CollectBut, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(CurrentCash, javax.swing.GroupLayout.DEFAULT_SIZE, 161, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(90, 90, 90)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(FillBut, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(CurrentTic, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(95, 95, 95))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(158, 158, 158))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(94, 94, 94)
                        .addComponent(SendBut, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(114, 114, 114)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel1)
                .addGap(12, 12, 12)
                .addComponent(CurrentCash)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(CollectBut)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(CurrentTic)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(FillBut)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(SendBut)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
/**
 * Collect the cash
 * @param evt 
 */
    private void CollectButMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CollectButMouseClicked
         if(((JButton)evt.getSource()).equals(this.CollectBut)){
            op.cashClear();
            this.currentCashRefresh();
            JOptionPane.showMessageDialog(null, "CashBox cleared","Cleared",JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_CollectButMouseClicked
/**
 * Fill the ticket
 * @param evt 
 */
    private void FillButMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_FillButMouseClicked
        if(((JButton)evt.getSource()).equals(this.FillBut)){
            op.fillTicket();
            this.currentTicketRefrsh();
            JOptionPane.showMessageDialog(null, "TicketBox Filled","Fill",JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_FillButMouseClicked
/**
 * Send the Bills to all Staff 
 * @param evt 
 */
    private void SendButActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SendButActionPerformed
        if(((JButton)evt.getSource()).equals(this.SendBut)){
                  op.generateMonthBill();
                  JOptionPane.showMessageDialog(null, "BillGenerated","Bill Info",JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_SendButActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CollectBut;
    private javax.swing.JLabel CurrentCash;
    private javax.swing.JLabel CurrentTic;
    private javax.swing.JButton FillBut;
    private javax.swing.JButton SendBut;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    // End of variables declaration//GEN-END:variables
}
