/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI;

import Entity.CashBox;
import Entity.ParkCntrl;
import javax.swing.JButton;
import javax.swing.JOptionPane;

/**
 *
 * @author Yongli Wang
 * @author Jingtai Li
 */
public class PayDialog extends javax.swing.JDialog {
    ParkCntrl op;

    /**
     * Creates new form PayDialog
     * @param parent
     * @param modal
     * @param op
     */
    public PayDialog(java.awt.Frame parent, boolean modal,ParkCntrl op) {
        super(parent, modal);
        this.op=op;
        initComponents();
        priceRefresh();
        paidRefresh();
        TimeInRefresh();
        this.setVisible(true);
    }

    /**
     *
     */
    public void priceRefresh(){
        this.TotalPri.setText("Total Price: "+op.getFee());
    }

    /**
     *
     */
    public void paidRefresh(){
        this.paid.setText("Paid: "+op.getPayFee());
    }

    /**
     *
     */
    public void TimeInRefresh(){
        this.TimeIn.setText("Time(In): "+op.getInDate());
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TimeIn = new javax.swing.JLabel();
        TotalPri = new javax.swing.JLabel();
        paid = new javax.swing.JLabel();
        pay50But = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        m50pL = new javax.swing.JLabel();
        m1L = new javax.swing.JLabel();
        m2L = new javax.swing.JLabel();
        pay2pBut = new javax.swing.JButton();
        pay1PBut = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        TimeIn.setText("Time(In):");

        TotalPri.setText("Total price:");

        paid.setText("Paid:");

        pay50But.setText("Fill a coin");
        pay50But.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pay50ButActionPerformed(evt);
            }
        });

        jLabel1.setText("Money Type:");

        jLabel2.setText("50p:");

        jLabel3.setText("1");

        jLabel4.setText("2");

        pay2pBut.setText("Fill a coin");
        pay2pBut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pay2pButActionPerformed(evt);
            }
        });

        pay1PBut.setText("Fill a coin");
        pay1PBut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pay1PButActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel2)
                        .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING))
                    .addComponent(paid))
                .addGap(90, 90, 90)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(pay1PBut)
                    .addComponent(pay50But)
                    .addComponent(pay2pBut))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(m50pL, javax.swing.GroupLayout.DEFAULT_SIZE, 65, Short.MAX_VALUE)
                    .addComponent(m1L, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(m2L, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(TimeIn)
                    .addComponent(jLabel1))
                .addGap(68, 68, 68)
                .addComponent(TotalPri)
                .addContainerGap(86, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TotalPri)
                    .addComponent(TimeIn))
                .addGap(24, 24, 24)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2)
                        .addComponent(pay50But))
                    .addComponent(m50pL, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pay1PBut)
                    .addComponent(jLabel3)
                    .addComponent(m1L, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pay2pBut)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel4)
                        .addComponent(m2L, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(paid)
                .addContainerGap(51, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
/**
 * Count the number that the JRadioButton has been clicked and show in the JTextField. 
 */   
/**
 * caculate the sum of paid
 * @param evt 
 */
    private void pay50ButActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pay50ButActionPerformed
        if(((JButton)evt.getSource()).equals(this.pay50But)){
            int result=op.pay(CashBox.TYPE_50);
            switch(result){
            case ParkCntrl.NOT_ENOUGH:
                priceRefresh();
                paidRefresh();
                break;
            case ParkCntrl.THIS_BOX_FULL:
                priceRefresh();
                paidRefresh();
                JOptionPane.showMessageDialog(null, "box of 50p is full","Failed",JOptionPane.ERROR_MESSAGE); 
                break;
            case ParkCntrl.SUCCESS:
                JOptionPane.showMessageDialog(null, "all Clear","Success",JOptionPane.INFORMATION_MESSAGE); 
                this.dispose();
                break;
            }
        }
    }//GEN-LAST:event_pay50ButActionPerformed

    private void pay2pButActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pay2pButActionPerformed
        if(((JButton)evt.getSource()).equals(this.pay2pBut)){
            int result=op.pay(CashBox.TYPE_2p);
            switch(result){
            case ParkCntrl.NOT_ENOUGH:
                priceRefresh();
                paidRefresh();
                break;
            case ParkCntrl.THIS_BOX_FULL:
                priceRefresh();
                paidRefresh();
                JOptionPane.showMessageDialog(null, "box of 2p is full","Failed",JOptionPane.ERROR_MESSAGE); 
                break;
            case ParkCntrl.SUCCESS:
                JOptionPane.showMessageDialog(null, "You are free to go now","Success",JOptionPane.INFORMATION_MESSAGE); 
                this.dispose();
                break;
            }
        }
    }//GEN-LAST:event_pay2pButActionPerformed

    private void pay1PButActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pay1PButActionPerformed
        if(((JButton)evt.getSource()).equals(this.pay1PBut)){
            int result=op.pay(CashBox.TYPE_1p);
            switch(result){
            case ParkCntrl.NOT_ENOUGH:
                priceRefresh();
                paidRefresh();
                break;
            case ParkCntrl.THIS_BOX_FULL:
                priceRefresh();
                paidRefresh();
                JOptionPane.showMessageDialog(null, "box of 1p is full","Failed",JOptionPane.ERROR_MESSAGE); 
                break;
            case ParkCntrl.SUCCESS:
                JOptionPane.showMessageDialog(null, "You are free to go now","Success",JOptionPane.INFORMATION_MESSAGE); 
                this.dispose();
                break;
            }
        }
    }//GEN-LAST:event_pay1PButActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel TimeIn;
    private javax.swing.JLabel TotalPri;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel m1L;
    private javax.swing.JLabel m2L;
    private javax.swing.JLabel m50pL;
    private javax.swing.JLabel paid;
    private javax.swing.JButton pay1PBut;
    private javax.swing.JButton pay2pBut;
    private javax.swing.JButton pay50But;
    // End of variables declaration//GEN-END:variables
}
